### ISSUE TITLE
Trying to build assembly error

### ISSUE THREAD

**Issue by bitsofinfo** [dacr/jassh#12]
Tried w/ both scala 2.10.5 and 2.11.5

```
[error] (*:update) sbt.ResolveException: unresolved dependency: fr.janalyse#janalyse-ssh_2.10;0.9.19: not found
```

**Comment by dacr** [comment]
don't forget to add this resolver : 

resolvers += "JAnalyse Repository" at "http://www.janalyse.fr/repository/"
