### ISSUE TITLE
ssh tasks prompt for kerberos username/password on linux redhat

### ISSUE THREAD

**Issue by herbinator** [dacr/jassh#13]
Making ssh connection on linux redhat with prompts for a kerberos username and password (which are then ignored if other credentials have already been supplied). On windows it all works great. 

found info: https://bz.apache.org/bugzilla/show_bug.cgi?id=53437
Adding the suggested solution works:
  session.setConfig("PreferredAuthentications", 
                  "publickey,keyboard-interactive,password");
in SSH.scala after ses.setTimeout(options.connectTimeout.toInt)
I tried the solution/work around and it works

**Comment by dacr** [comment]
taken into account, thanks for you contribution. Will be available in 0.9.19-SNAPSHOT in a few minutes.

**Comment by jcut** [comment]
@dacr I really want to use 0.9.19-SNAPSHOT for this bug fix.
at the moment I'm building the project on my local machine, when do you think it will be in the repo?

Thanks.

**Comment by dacr** [comment]
done. take care with latest sshd/openssl, I got issues linked to jsch...
waiting for a patch.
regards,
David.

2015-09-22 9:34 GMT+02:00 jcut <notifications@github.com>:
