### ISSUE TITLE
SSHFtp#receive provides no operation result status

### ISSUE THREAD

**Issue by andrebeat** [dacr/jassh#16]
The more general `receive` method in `SSHFtp` (https://github.com/dacr/jassh/blob/master/src/main/scala/fr/janalyse/ssh/SSHFtp.scala#L86) handles all the exceptions internally and doesn't return any value. This makes it impossible to know whether a file download was successful or not. 

I'd recommend either returning a value (a boolean?) or removing the exception handling code so that the caller can deal with the error cases.

Do you think that makes sense?

**Comment by dacr** [comment]
yes, it makes senses. I leave the log and rethrow the same exception.
