### ISSUE TITLE
no main manifest attribute, in target/scala-2.11/jassh.jar

### ISSUE THREAD

**Issue by joyfulmonster** [dacr/jassh#18]
My sbt assembly ran fine.   However, when I following the doc and do 

java -jar target/scala-2.11/jassh.jar

I got the "no main manifest attribute, in target/scala-2.11/jassh.jar" error.   Did I miss anything?   My java is 1.8.0_92.

**Comment by dacr** [comment]
no you're right... I'll investigate.
```
00:30 $ java -jar target/scala-2.11/jassh.jar 
aucun attribut manifest principal dans target/scala-2.11/jassh.jar
```

**Comment by dacr** [comment]
OK I'm going to put back the "onejar" subdirectory that should be used in order to generate an executable jar which comes with the scala console dependencies.
